Update to latest infrastructure tools.
I accidentally broke website updating by deleting a personal GitHub token,
so I had to give the lambda a new token.

Sadly, this repo hasn't gotten a lot of attention from me. This is good,
in the sense that the infrastructure it set up has been quietly
working for a year or two now! But dependencies don't stop moving
because your work is complete. They're like sharks! They've gotta keep
swimming!

As a result, I had to update my dependencies: this meant (finally) tackling
the Terraform 0.13 migration, upgrading to the latest OnePassword CLI (which
is admittedly much nicer!), and upgrading all of the providers in this repo.

So, a yak shake of a yak shave of a yak shake, found while on my way to shave
another yak. This is my hobby!

diff --git a/bin/activate-credentials b/bin/activate-credentials
--- a/bin/activate-credentials
+++ b/bin/activate-credentials
@@ -1,42 +1,27 @@
 #!/bin/bash
 
-# Dials and knobs: Allow configuration of which domain, vault, and item to
-# fetch. Treat "TEAM.1password.com" domain input the same as "TEAM" because
-# that can be super confusing.
-op_domain=${ONEPASSWORD_DOMAIN:-my}
-op_domain_replaced=${op_domain/1password.com//}
 op_vault=${ONEPASSWORD_VAULT:-Personal}
 op_item=${ONEPASSWORD_ITEM:-credentials.env}
 
-if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-  signin=$(op signin $op_domain_replaced.1password.com)
+if op whoami &>/dev/null; then
+  item=$(op item get --format json credentials.env | jq '.fields[] | select(.id == "notesPlain") | .value' -r)
   result=$?
-  if [ $result -ne 0 ]; then
-    echo -e "\x1b[31mFailed to signin.\x1b[0m"
-    echo "$signin"
-  else
-    eval "$signin"
-    item=$(op get item --vault=${op_vault} ${op_item} .env | jq '.details.notesPlain' -r)
+  if [ $result -eq 0 ]; then
+    eval "$item"
     result=$?
-    if [ $result -eq 0 ]; then
-      eval "$item"
-      result=$?
-      if [ $result -ne 0 ]; then
-        echo -e "\x1b[31mFailed to evaluate credentials. \x1b[0m Check the following script for errors & correct them in 1Password's UI:"
-        echo "======== output ========="
-        echo "$item"
-        echo "====== end output ======="
-      else
-        echo -e "\x1b[32mActivated.\x1b[0m"
-        export PS1="\033[31m(creds)\033[0m $PS1"
-      fi
+    if [ $result -ne 0 ]; then
+      echo -e "\x1b[31mFailed to evaluate credentials. \x1b[0m Check the following script for errors & correct them in 1Password's UI:"
+      echo "======== output ========="
+      echo "$item"
+      echo "====== end output ======="
     else
-
-      echo -e "\x1b[31mFailed to fetch "'"'"${op_item}"'"'".\x1b[0m Does this item exist in your "'"'"${op_vault}"'"'" 1pass vault?"
+      echo -e "\x1b[32mActivated.\x1b[0m"
+      export PS1="\033[31m(creds)\033[0m $PS1"
     fi
-    op signout ${op_domain_replaced}.1password.com
-    eval "unset OP_SESSION_${op_domain_replaced}"
+  else
+
+    echo -e "\x1b[31mFailed to fetch "'"'"${op_item}"'"'".\x1b[0m Does this item exist in your "'"'"${op_vault}"'"'" 1pass vault?"
   fi
 else
-  echo "You must source this script; it cannot be run on its own."
+  >&2 echo 'run "eval $(op signin)" and then re-source this file.'
 fi
